slick.dbs.default.profile = "slick.jdbc.SQLiteProfile$"
slick.dbs.default.db.driver = "org.sqlite.JDBC"
slick.dbs.default.db.url = "jdbc:sqlite:argos_auditoria.db"
slick.dbs.default.db.connectionPool = disabled
slick.dbs.default.db.keepAliveConnection = true
play.filters.headers.contentSecurityPolicy = null